[Icon Theme]
Name=ovİcons
Inherits=hicolor
Directories=actions,categories,devices,emblems,mimetypes,places

[actions]
Context=Actions
Size=64
Scale=1
Type=Scalable

[categories]
Context=Categories
Size=64
Scale=1
Type=Scalable

[devices]
Context=Devices
Size=64
Scale=1
Type=Scalable

[emblems]
Context=Emblems
Size=64
Scale=1
Type=Scalable

[mimetypes]
Context=Mimetypes
Size=64
Scale=1
Type=Scalable

[places]
Context=Places
Size=64
Scale=1
Type=Scalable